// Next
import Head from "next/head";

// React
import { useState } from "react";

// React-Icons
import {
  WiThermometer,
  WiSprinkle,
  WiBarometer,
  WiStrongWind,
} from "react-icons/wi";

// Components
import TabsItem from "../components/tabs/TabsItem";
import Temperature from "../components/charts/temperature";
import Humidity from "../components/charts/humidity";
import Pressure from "../components/charts/pressure";
import H2S from "../components/charts/H2S";

const Tabs = Object.freeze({
  Temperature: "Temperature",
  Humidity: "Humidity",
  Pressure: "Pressure",
  H2S: "H2S",
});

export default function Home() {
  const [tab, setTab] = useState(Tabs.Temperature);

  const myRouter = () => {
    switch (tab) {
      case Tabs.Temperature:
        return <Temperature />;
      case Tabs.Humidity:
        return <Humidity />;
      case Tabs.Pressure:
        return <Pressure />;
      case Tabs.H2S:
        return <H2S />;
      default:
        return <h3>Something went wrong...</h3>;
    }
  };

  return (
    <div className="h-screen w-screen">
      <Head>
        <title>BadBoyRune</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mx-2 md:mx-0 border-b border-gray-200 dark:border-gray-700">
          <ul className="flex justify-center -mb-px text-sm font-medium text-center text-gray-500 dark:text-gray-400">
            <TabsItem
              label={Tabs.Temperature}
              Icon={WiThermometer}
              setActive={() => setTab(Tabs.Temperature)}
              active={Tabs.Temperature === tab}
            />
            <TabsItem
              label={Tabs.Humidity}
              Icon={WiSprinkle}
              setActive={() => setTab(Tabs.Humidity)}
              active={Tabs.Humidity === tab}
            />
            <TabsItem
              label={Tabs.Pressure}
              Icon={WiBarometer}
              setActive={() => setTab(Tabs.Pressure)}
              active={Tabs.Pressure === tab}
            />
            <TabsItem
              label={Tabs.H2S}
              Icon={WiStrongWind}
              setActive={() => setTab(Tabs.H2S)}
              active={Tabs.H2S === tab}
            />
          </ul>
        </div>
        <div className="md:w-1/2 mx-auto p-5">{myRouter()}</div>
      </main>

      <footer></footer>
    </div>
  );
}
